version: '3.8'

volumes:
  pg-data:

services:
  pg:
    image: postgres:14.7-alpine
    restart: on-failure
    ports:
      - ${PG_PORT}:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
  